<?php

namespace Inass\EleccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRepository extends EntityRepository
{
    public function findAllOrderedByNombre()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT e FROM EleccionBundle:Estado e ORDER BY e.nombre ASC')
            ->getResult();
    }
}
